from django import forms
from django.forms import ModelForm
from django.core.exceptions import ValidationError

CAT_BREED_CHOICES = (
    ('ABYSSINIAN', 'Abyssinian'), ('AMERICAN-CURL', 'American-Curl'), 
    ('AMERICAN-SHORTHAIR', 'American-Shorthair'),('AMERICAN-WIREHAIR', 'American-Wirehair'),('APPLEHEAD-SIAMESE', 'Applehead-Siamese'),('BALINESE', 'Balinese'),('BENGAL', 'Bengal'),('Birman','Birman'),
    ('BOBTAIL','Bobtail'),('BOMBAY', 'Bombay'),('BRITISH-SHORTHAIR','British-Shorthair'),('BURMESE','Burmese'),('BURMILLA','Burmilla'),('CALICO','Calico'),('CANADIAN-HAIRLESS','Canadian-Hairless'),('CHARTEAUX','Chartreux'),('CHAUSIE','Chausie'),('CHINCHILLA','Chinchilla'),('CORNISH-Rex','Cornish-Rex'),('CYMRIC','Cymric'),
    ('DEVON-REX','Devon-Rex'),('DILUTE-CALICO','Dilute-Calico'),
    ('DILUTE-TORTOISESHELL','Dilute-Tortoiseshell'),('DOMESTIC-LONG-HAIR','Domestic-Long-Hair'),('DOMESTIC-MEDIUM-','Domestic-Medium-Hair'), ('DOMESTIC-SHORT-HAIR','Domestic-Short-Hair'),('EGYPTIAN-MAU','Egyptian-Mau'),('Exotic-Shorthair'),('EXTRA-TOES-CAT/HEMINGWAY-POLYDACTYL','Extra-Toes-Cat/Hemingway-Polydactyl'),('HAVANA','Havana'),
    ('HIMALAYAN','Himalayan'),('JAPANESE-BOBTAIL','Japanese-Bobtail'),
    ('JAVANESE','Javanese'),('KORAT','Korat'),('LAPERM','LaPerm'),('MAINE-COON','Maine-Coon'),('MANX','Manx'),('MUNCHKIN','Munchkin'),
    ('NEBELUNG','Nebelung'),('NORWEGIAN-FOREST-CAT','Norwegian-Forest-Cat'),('OCICAT','Ocicat'),('ORIENTAL-LONG-HAIR','Oriental-Long-Hair'),('ORIENTAL-SHORT-HAIR','Oriental Short Hair'),
    ('ORIENTAL-TABBY','Oriental-Tabby'),('PERSIAN','Persian'),('PIXIE-BOB','Pixie-Bob'),('RAGAMUFFIN','Ragamuffin'),('RAGDOLL','Ragdoll'),('RUSSIAN-BLUE','Russian-Blue'),('SCOTTISH-FOLD','Scottish-Fold'),('SELKIRK-REX','Selkirk-Rex'),('SIAMESE','Siamese'),
    ('SIBERIAN','Siberian'),('SILVER','Silver'),('SINGAPURA','Singapura'),('SNOWSHOE','Snowshoe'),('SOMALI','Somali'),('SPHYNX/HAIRLESS-CAT','Sphynx/Hairless-Cat'),('TABBY','Tabby'),('TIGER','Tiger'),
    ('TOKINESE','Tonkinese'),('TORBIE','Torbie'),('TORTOISESHELL','Tortoiseshell'),('TURKISH-ANGORA','Turkish-Angora'),
    ('TURKISH_VAN','Turkish_Van'),('TUXEDO','Tuxedo')
)

DOG_BREED_CHOICES = (
    ( 'AFFENPINSCHER' ,  'Affenpinscher' ),( 'AFGHAN-HOUND' ,  'Afghan-Hound' ),
    ( 'AIREDALE-TERRIER' ,  'Airedale-Terrier' ),( 'AKBASH' ,  'Akbash' ),( 'AKITA' ,  'Akita' ),
    ( 'ALASKAN-MALAMUTE' ,  'Alaskan-Malamute' ),( 'AMERICAN-BULLDOG' ,  'American-Bulldog' ),
    ( 'AMERICAN-ESKIMO-DOG' ,  'American-Eskimo-Dog' ),( 'AMERICAN-HAIRLESS-TERRIER' ,  'American-Hairless-Terrier' ),( 'AMERICAN-STAFFORDSHIRE-TERRIER' ,  'American-Staffordshire-Terrier' ),( 'AMERICAN-WATER-SPANIEL' ,  'American-Water-Spaniel' ),
    ( 'ANATOLIAN-SHEPHERD' ,  'Anatolian-Shepherd' ),( 'APPENZELL-MOUNTAIN-DOG' ,  'Appenzell-Mountain-Dog' ),( 'AUSTRALIAN-CATTLE-DOG/BLUE-HEELER' ,  'Australian-Cattle-Dog/Blue-Heeler' ),( 'AUSTRALIAN-KELPIE' ,  'Australian-Kelpie' ),
    ( 'AUSTRALIAN-SHEPHERD' ,  'Australian-Shepherd' ),( 'AUSTRALIAN-TERRIER' ,  'Australian-Terrier' ),( 'BASENJI' ,  'Basenji' ),( 'BASSET-HOUND' ,  'Basset-Hound' ),
    ( 'BEAGLE' ,  'Beagle' ),( 'BEARDED-COLLIE' ,  'Bearded-Collie' ),( 'BEAUCERON' ,  'Beauceron' ),( 'BEDLINGTON-TERRIER' ,  'Bedlington-Terrier' ),( 'BELGIAN-SHEPHERD/LAEKENOIS' ,  'Belgian-Shepherd/Laekenois' ),( 'BELGIAN-SHEPHERD/MALINOIS' ,  'Belgian-Shepherd/Malinois' ),( 'BELGIAN-SHEPHERD/SHEEPDOG' ,  'Belgian-Shepherd/Sheepdog' ),
    ( 'BELGIAN-SHEPHERD/TERVUREN' ,  'Belgian-Shepherd/Tervuren' ),( 'BERNESE-MOUNTAIN DOG' ,  'Bernese-Mountain Dog' ),( 'BICHON-FRISE' ,  'Bichon-Frise' ),('BLACK-AND-TAN-COONHOUNDBLACK-LABRADOR-RETRIEVER' 'Black-and-Tan-CoonhoundBlack-Labrador-Retriever' ),( 'BLACK-MOUTH-CUR' ,  'Black-Mouth-Cur' ),( 'BLACK-RUSSIAN-TERRIER' ,  'Black-Russian-Terrier' ),( 'BLOODHOUND' ,  'Bloodhound' ),
    ( 'BLUE-LACY' ,  'Blue-Lacy' ),( 'BLUETICK-COONHOUND' ,  'Bluetick-Coonhound' ),
    ( 'BOERBOEL' ,  'Boerboel' ),( 'BOLOGNESE' ,  'Bolognese' ),( 'BORDER-COLLIE' ,  'Border-Collie' ),( 'BORDER-TERRIER' ,  'Border-Terrier' ),( 'BORZOI' ,  'Borzoi' ),
    ( 'BOSTON-TERRIER' ,  'Boston-Terrier' ),( 'BOUVIER-DES-FLANDERS' ,  'Bouvier-des-Flanders' ),
    ( 'BOXER' ,  'Boxer' ),( 'BOYKIN-SPANIEL' ,  'Boykin-Spaniel' ),( 'BRIARD' ,  'Briard' ),
    ( 'BRITTANY-SPANIEL' ,  'Brittany-Spaniel' ),( 'BRUSSELS-GRIFFON' ,  'Brussels-Griffon' ),
    ( 'BULL-TERRIER' ,  'Bull-Terrier' ),( 'BULLMASTIFF' ,  'Bullmastiff' ),( 'CAIRN-TERRIER' ,  'Cairn-Terrier' ),( 'CANAAN-DOG' ,  'Canaan-Dog' ),( 'CANE-CORSO-MASTIFF' ,  'Cane-Corso-Mastiff' ), ( 'CAROLINA-DOG' ,  'Carolina-Dog' ),( 'CATAHOULA-LEOPARD-DOG' ,  'Catahoula-Leopard-Dog' ),( 'CATTLE-DOG' ,  'Cattle-Dog' ),
    ( 'CAUCASIAN-SHEEPDOG/CAUCASIAN-OVTCHARKA' ,  'Caucasian-Sheepdog/Caucasian-Ovtcharka' ),
    ( 'CAVALIER-KING-CHARLES-SPANIEL' ,  'Cavalier-King-Charles-Spaniel' ),
    ( 'CHESAPEAKE-BAY-RETRIEVER' ,  'Chesapeake-Bay-Retriever' ),( 'CHIHUAHUA' ,  'Chihuahua' ),
    ( 'CHINESE-CRESTED-DOG' ,  'Chinese-Crested-Dog' ),( 'CHINESE-FOO-DOG' ,  'Chinese-Foo-Dog' ),( 'CHINOOK' ,  'Chinook' ),( 'CHOCOLATE-LABRADOR-RETRIEVER' ,  'Chocolate-Labrador-Retriever' ),( 'CHOW-CHOW' ,  'Chow-Chow' ),( 'CIRNECO-DELL' ,  'Cirneco-dell' ),( 'CLUMBER-SPANIEL' ,  'Clumber-Spaniel' ),( 'COCKAPOO' ,  'Cockapoo' ),( 'COCKER-SPANIEL' ,  'Cocker-Spaniel' ),
    ( 'COLLIE' ,  'Collie' ),( 'COONHOUND' ,  'Coonhound' ),( 'CORGI' ,  'Corgi' ),
    ( 'COTON-DE-TULEAR' ,  'Coton-de-Tulear' ),( 'CURLY-COATED RETRIEVER' ,  'Curly-Coated Retriever' ),( 'DACHSHUND' ,  'Dachshund' ),( 'DALMATIAN' ,  'Dalmatian' ),
    ( 'DANDI-DINMONT-TERRIER' ,  'Dandi-Dinmont-Terrier' ),( 'DOBERMAN-PINSCHER' ,  'Doberman-Pinscher' ),( 'DOGO-ARGENTINO' ,  'Dogo-Argentino' ),( 'DOGUE-DE-BORDEAUX' ,  'Dogue-de-Bordeaux' ),( 'DUTCH-SHEPHERD' ,  'Dutch-Shepherd' ),( 'ENGLISH-BULLDOG' ,  'English-Bulldog' ),( 'ENGLISH-COCKER-SPANIEL' ,  'English-Cocker-Spaniel' ),( 'ENGLISH-COONHOUND' ,  'English-Coonhound' ),( 'ENGLISH-POINTER' ,  'English-Pointer' ),
    ( 'ENGLISH-SETTER' ,  'English-Setter' ),( 'ENGLISH-SHEPHERD' ,  'English-Shepherd' ),
    ( 'ENGLISH-SPRINGER-SPANIEL' ,  'English-Springer-Spaniel' ),( 'ENGLISH-TOY-SPANIEL' ,  'English-Toy-Spaniel' ),( 'ENTLEBUCHER' ,  'Entlebucher' ),( 'ESKIMO-DOG' ,  'Eskimo-Dog' ),
    ( 'FEIST' ,  'Feist' ),( 'FIELD-SPANIEL' ,  'Field-Spaniel' ),( 'FILA-BRASILEIRO' ,  'Fila-Brasileiro' ),( 'FINNISH-LAPPHUND' ,  'Finnish-Lapphund' ),( 'FINNISH-SPITZ' ,  'Finnish-Spitz' ),( 'FLAT-COATED-RETRIEVER' ,  'Flat-Coated-Retriever' ),
    ( 'FOX-TERRIER' ,  'Fox-Terrier' ),( 'FOXHOUND' ,  'Foxhound' ),( 'FRENCH-BULLDOG' ,  'French-Bulldog' ),( 'GALGO-SPANISH-GREYHOUND' ,  'Galgo-Spanish-Greyhound' ),
    ( 'GERMAN-PINSCHER' ,  'German-Pinscher' ),( 'GERMAN-SHEPHERD-DOG' ,  'German-Shepherd-Dog' ),
    ( 'GERMAN-SHORTHAIRED-POINTER' ,  'German-Shorthaired-Pointer' ),( 'GERMAN-SPITZ' ,  'German-Spitz' ),( 'GERMAN-WIREHAIRED-POINTER' ,  'German-Wirehaired-Pointer' ),
    ( 'GIANT-SCHNAUZER' ,  'Giant-Schnauzer' ),( 'GLEN-OF-IMAAL-TERRIER' ,  'Glen-of-Imaal-Terrier' ),( 'GOLDEN-RETRIEVER' ,  'Golden-Retriever' ),( 'GORDON-SETTER' ,  'Gordon-Setter' ),( 'GREAT-DANE' ,  'Great-Dane' ),( 'GREAT-PYRENEES' ,  'Great-Pyrenees' ),
    ( 'GREATER-SWISS-MOUNTAIN-DOG' ,  'Greater-Swiss-Mountain-Dog' ),( 'GREYHOUND' ,  'Greyhound' ),( 'HAMILTONSTOVARE' ,  'Hamiltonstovare' ),( 'HARRIER' ,  'Harrier' ),( 'HAVANESE' ,  'Havanese' ),( 'HOUND' ,  'Hound' ),( 'HOVAWART' ,  'Hovawart' ),( 'HUSKY' ,  'Husky' ),
    ( 'IBIZAN-HOUND' ,  'Ibizan-Hound' ),( 'ICELANDIC-SHEEPDOG' ,  'Icelandic-Sheepdog' ),
    ( 'ILLYRIAN-SHEEPDOG' ,  'Illyrian-Sheepdog' ),( 'IRISH-SETTER' ,  'Irish-Setter' ),
    ( 'IRISH-TERRIER' ,  'Irish-Terrier' ),( 'IRISH-WATER-SPANIEL' ,  'Irish-Water-Spaniel' ),
    ( 'IRISH-WOLFHOUND' ,  'Irish-Wolfhound' ),( 'ITALIAN-GREYHOUND' ,  'Italian-Greyhound' ),
    ( 'ITALIAN-SPINONE' ,  'Italian-Spinone' ),( 'JACK-RUSSELL-TERRIER' ,  'Jack-Russell-Terrier' ),( 'JACK-RUSSELL-TERRIER-(PARSON)' ,  'Jack-Russell-Terrier-(Parson)' ),( 'JAPANESE-CHIN' ,  'Japanese-Chin' ),( 'JINDO' ,  'Jindo' ),( 'KAI-DOG' ,  'Kai-Dog' ),( 'KARELIAN-BEAR-DOG' ,  'Karelian-Bear-Dog' ),( 'KEESHOND' ,  'Keeshond' ),( 'KERRY-BLUE-TERRIER' ,  'Kerry-Blue-Terrier' ),( 'KISHU' ,  'Kishu' ),( 'KLEE-KAI' ,  'Klee-Kai' ),( 'KOMONDOR' ,  'Komondor' ),( 'KUVASZ' ,  'Kuvasz' ),( 'KYI-LEO' ,  'Kyi-Leo' ),( 'LABRADOR-RETRIEVER' ,  'Labrador-Retriever' ),( 'LAKELAND-TERRIER' ,  'Lakeland-Terrier' ),( 'LANCASHIRE-HEELER' ,  'Lancashire-Heeler' ),( 'LEONBERGER' ,  'Leonberger' ),( 'LHASA-APSO' ,  'Lhasa-Apso' ),
    ( 'LOWCHEN' ,  'Lowchen' ),( 'MALTESE' ,  'Maltese' ),( 'MANCHESTER-TERRIER' ,  'Manchester-Terrier' ),( 'MAREMMA-SHEEPDOG' ,  'Maremma-Sheepdog' ),( 'MASTIFF' ,  'Mastiff' ),( 'MCNAB' ,  'McNab' ),( 'MINIATURE-PINSCHER' ,  'Miniature-Pinscher' ),( 'MINIATURE-SCHNAUZERMIXED-BREED' ,  'Miniature-SchnauzerMixed-Breed' ),
    ( 'MOUNTAIN-CUR' ,  'Mountain-Cur' ),( 'MOUNTAIN-DOG' ,  'Mountain-Dog' ),( 'MUNSTERLANDER' ,  'Munsterlander' ),( 'NEAPOLITAN-MASTIFF' ,  'Neapolitan-Mastiff' ), ( 'NEW-GUINEA-SINGING-DOG' ,  'New-Guinea-Singing-Dog' ),( 'NEWFOUNDLAND-DOG' ,  'Newfoundland-Dog' ),( 'NORFOLK-TERRIER' ,  'Norfolk-Terrier' ),( 'NORWEGIAN-BUHUND' ,  'Norwegian-Buhund' ),( 'NORWEGIAN-ELKHOUND' ,  'Norwegian-Elkhound' ),( 'NORWEGIAN-LUNDEHUND' ,  'Norwegian-Lundehund' ),( 'NORWICH-TERRIER' ,  'Norwich-Terrier' ),
    ( 'NOVA-SCOTIA-DUCK-TOLLING-RETRIEVER' ,  'Nova-Scotia-Duck-Tolling-Retriever' ),
    ( 'OLD-ENGLISH-SHEEPDOG' ,  'Old-English-Sheepdog' ),( 'OTTERHOUND' ,  'Otterhound' ),
    ( 'PAPILLON' ,  'Papillon' ),( 'PATTERDALE-TERRIER/FELL-TERRIER' ,  'Patterdale-Terrier/Fell-Terrier' ),( 'PEKINGESE' ,  'Pekingese' ),( 'PERUVIAN-INCA-ORCHID' ,  'Peruvian-Inca-Orchid' ),( 'PETIT-BASSET-GRIFFON-VENDEEN' ,  'Petit-Basset-Griffon-Vendeen' ),( 'PHARAOH-HOUND' ,  'Pharaoh-Hound' ),( 'PIT-BULL-TERRIER' ,  'Pit-Bull-Terrier' ),
    ( 'PLOTT-HOUND' ,  'Plott-Hound' ),( 'PODENGO-PORTUGUESO' ,  'Podengo-Portugueso' ),
    ( 'POINTER' ,  'Pointer' ),( 'POLISH-LOWLAND-SHEEPDOG' ,  'Polish-Lowland-Sheepdog' ),
    ( 'POMERANIAN' ,  'Pomeranian' ),( 'POODLE' ,  'Poodle' ),( 'PORTUGUESE-WATER-DOG' ,  'Portuguese-Water-Dog' ),( 'PRESA-CANARIO' ,  'Presa-Canario' ),( 'PUG' ,  'Pug' ),
    ( 'PULI' ,  'Puli' ),( 'PUMI' ,  'Pumi' ),( 'RAT-TERRIER' ,  'Rat-Terrier' ),
    ( 'REDBONE-COONHOUND' ,  'Redbone-Coonhound' ),( 'RETRIEVER' ,  'Retriever' ),
    ( 'RHODESIAN-RIDGEBACK' ,  'Rhodesian-Ridgeback' ),( 'ROTTWEILER' ,  'Rottweiler' ),
    ( 'ROUGH-COLLIE' ,  'Rough-Collie' ),( 'SAINT-BERNARD/ST.-BERNARD' ,  'Saint-Bernard/St.-Bernard' ),( 'SALUKI' ,  'Saluki' ),( 'SAMOYED' ,  'Samoyed' ),
    ( 'SARPLANINAC' ,  'Sarplaninac' ),( 'SCHIPPERKE' ,  'Schipperke' ),( 'SCHNAUZER' ,  'Schnauzer' ),( 'SCOTTISH-DEERHOUND' ,  'Scottish-Deerhound' ),( 'SCOTTISH-TERRIER-SCOTTIE' ,  'Scottish-Terrier-Scottie' ),( 'SEALYHAM-TERRIER' ,  'Sealyham-Terrier' ),( 'SETTER' ,  'Setter' ),( 'SHAR-PEI' ,  'Shar-Pei' ),( 'SHEEP-DOG' ,  'Sheep-Dog' ),( 'SHEPHERD' ,  'Shepherd' ),( 'SHETLAND-SHEEPDOG-SHELTIE' ,  'Shetland-Sheepdog-Sheltie' ),( 'SHIBA-INU' ,  'Shiba-Inu' ),( 'SHIH-TZU' ,  'Shih-Tzu' ),( 'SIBERIAN-HUSKY' ,  'Siberian-Husky' ),
    ( 'SILKY-TERRIER' ,  'Silky-Terrier' ),( 'SKYE-TERRIER' ,  'Skye-Terrier' ),
    ( 'SLOUGHI' ,  'Sloughi' ),( 'SMOOTH-COLLIE' ,  'Smooth-Collie' ),( 'SMOOTH-FOX-TERRIER' ,  'Smooth-Fox-Terrier' ),( 'SOUTH-RUSSIAN-OVTCHARKA' ,  'South-Russian-Ovtcharka' ),
    ( 'SPANIEL' ,  'Spaniel' ),( 'SPANISH-WATER-DOG' ,  'Spanish-Water-Dog' ),( 'SPITZ' ,  'Spitz' ),( 'STAFFORDSHIRE-BULL-TERRIER' ,  'Staffordshire-Bull-Terrier' ),
    ( 'STANDARD-POODLE' ,  'Standard-Poodle' ),( 'STANDARD-SCHNAUZER' ,  'Standard-Schnauzer' ),
    ( 'SUSSEX-SPANIEL' ,  'Sussex-Spaniel' ),( 'SWEDISH-VALLHUND' ,  'Swedish-Vallhund' ),
    ( 'TERRIER' ,  'Terrier' ),( 'THAI-RIDGEBACK' ,  'Thai-Ridgeback' ),( 'TIBETAN-MASTIFF' ,  'Tibetan-Mastiff' ),( 'TIBETAN-SPANIEL' ,  'Tibetan-Spaniel' ),( 'TIBETAN-TERRIER' ,  'Tibetan-Terrier' ),( 'TOSA-INU' ,  'Tosa-Inu' ),( 'TOY-FOX-TERRIER' ,  'Toy-Fox-Terrier' ),
    ( 'TREEING-WALKER-COONHOUND' ,  'Treeing-Walker-Coonhound' ),( 'VIZSLA' ,  'Vizsla' ),
    ( 'WEIMARANER' ,  'Weimaraner' ),( 'WELSH-CORGI' ,  'Welsh-Corgi' ),
    ( 'WELSH-SPRINGER-SPANIEL' ,  'Welsh-Springer-Spaniel' ),( 'WELSH-TERRIER' ,  'Welsh-Terrier' ),( 'WEST-HIGHLAND-WHITE-TERRIER-WESTIE' ,  'West-Highland-White-Terrier-Westie' ),
    ( 'WHEATEN-TERRIER' ,  'Wheaten-Terrier' ),( 'WHIPPET' ,  'Whippet' ),
    ( 'WHITE-GERMAN-SHEPHERD' ,  'White-German-Shepherd' ),( 'WIRE-FOX-TERRIER' ,  'Wire-Fox-Terrier' ),( 'WIREHAIRED-DACHSHUND' ,  'Wirehaired-Dachshund' ),
    ( 'WIREHAIRED-POINTING-GRIFFON' ,  'Wirehaired-Pointing-Griffon' ),( 'WIREHAIRED-TERRIER' ,  'Wirehaired-Terrier' ),( 'XOLOITZCUINTLE/MEXICAN-HAIRLESS' ,  'Xoloitzcuintle/Mexican-Hairless' ),( 'YELLOW-LABRADOR-RETRIEVER' ,  'Yellow-Labrador-Retriever' ),( 'YORKSHIRE-TERRIER-YORKIE' ,  'Yorkshire-Terrier-Yorkie' ),
)

